export const GET_CONTRIES_SUCCESS = "GET_CONTRIES_SUCCESS"
export const GET_CONTRIES_ERROR = "GET_CONTRIES_ERROR"
export const GET_CONTRIES = "GET_CONTRIES"
export const GET_CONTRIES_START = "GET_CONTRIES_START";